reqs file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,6 +17,13 @@ jobs:
         with:
           python-version: 3.12
 
+      - name: Check for requirements.txt
+        run: |
+          if [ ! -f "requirements.txt" ]; then 
+            echo "requirements.txt not found. Please add the file to the root of your repository."; 
+            exit 1; 
+          fi
+
       - name: Install dependencies
         run: pip install -r requirements.txt
 
